blank_issues_enabled: false
contact_links:
  - name: Discord
    url: 
    about: Discord is best for more in-depth discussions, so this will link you to the invite
  - name: Bug Reports/ Suggestions
    url: 
    about: if possible, put ideas, bugs, and more on discord server if possible. if not, then use github (but, response time will be slower)
