blank_issues_enabled: false
contact_links:
  - name: Discord
    url: 
    about: Discord is best for more in-depth discussions, so this will link you to the invite
  - name: Prefered Suggestion Location (my discord server, in rimworld mods section)
    url: 
    about: as suggestions easily lead to concepts and irl brainstorms, its prefered that you use discord for them. if you prefer, you can use the github form or the steam page
